### ISSUE TITLE
Remove deprecated features [Tracking issue]

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#348]
All deprecated modules (except those necessary for handling old transaction version if they remain supported) should be removed entirely from starknet.py.

Checklist with deprecated features:
- [x] #462
- [x] `AccountClient.create_account`
- [x] `version` field in the `TransactionReceipt`
- [x] #461
- [x] make_declare_tx
- [x] make_deploy_tx
- [x] #632 
- [x] #685  
- [x] #664 
- [x] #768
- [x] #791 
- [x] #792
- [x] #921 
- [x] #922
- [x] #923
- [x] #924
- [x] #925
- [x] #926
- [x] #927
